### ISSUE TITLE
Add few fields in `package.json`

### ISSUE THREAD

**Issue by ehmicky** [philhawksworth/netlify-plugin-trello-lists#1]
The following fields are missing from `package.json` (see [documentation](https://github.com/netlify/build#publishing-a-plugin)): `repository`, `bugs` and also a `"netlify-plugin"` in `keywords`.

Those fields help with the error reporting and also with finding the plugin on npmjs.com. Would it be possible to add them? Thanks!

**Comment by philhawksworth** [comment]
Oh thanks! Will do.
